# Generated by Django 4.2.23 on 2025-06-18 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField()),
                ('fps_num', models.IntegerField()),
                ('fps_den', models.IntegerField()),
                ('resolution', models.CharField(max_length=50)),
                ('file_path', models.FilePathField(max_length=500, path='./data/videos/', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_frame', models.IntegerField()),
                ('end_frame', models.IntegerField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoSearch.video')),
            ],
        ),
    ]
