# Generated by Django 4.2.23 on 2025-06-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoSearch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
        migrations.AddField(
            model_name='video',
            name='frame_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
