# Generated by Django 5.2.3 on 2025-06-19 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoSearch', '0002_remove_video_duration_video_frame_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipPredictionCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilities', models.BinaryField()),
                ('clip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='VideoSearch.clip')),
            ],
        ),
        migrations.CreateModel(
            name='Keyframe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.IntegerField()),
                ('embedding_clip', models.BinaryField()),
                ('embedding_dino', models.BinaryField(blank=True, null=True)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoSearch.clip')),
            ],
            options={
                'unique_together': {('clip', 'frame')},
            },
        ),
    ]
