# Generated by Django 5.2.3 on 2025-06-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoSearch', '0003_clippredictioncache_keyframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyframe',
            name='colorfulness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyframe',
            name='dominant_colors',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyframe',
            name='histogram_hsv',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
