# Generated by Django 5.2.3 on 2025-06-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoSearch', '0004_keyframe_colorfulness_keyframe_dominant_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyframe',
            name='object_labels',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
