# Generated by Django 5.2.3 on 2025-06-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoSearch', '0005_keyframe_object_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyframe',
            name='object_labels',
        ),
        migrations.AddField(
            model_name='keyframe',
            name='object_vector',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
