# Generated by Django 5.2.3 on 2025-08-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoSearch', '0006_remove_keyframe_object_labels_keyframe_object_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='web_path',
            field=models.FilePathField(blank=True, max_length=500, null=True, path='./data/videos_web/'),
        ),
    ]
