# Generated by Django 5.2.3 on 2025-08-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoSearch', '0007_video_web_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file_path',
            field=models.FilePathField(max_length=500, unique=True),
        ),
    ]
