# Generated by Django 5.2.3 on 2025-08-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoSearch', '0008_alter_video_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFolderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this media folder', max_length=100, unique=True)),
                ('path', models.CharField(help_text='Full path to the media folder', max_length=500)),
                ('recursive', models.BooleanField(default=True, help_text='Scan subdirectories recursively')),
                ('extensions', models.CharField(default='mp4,mov,mkv,avi,wmv,flv,webm,m4v', help_text='Comma-separated list of video file extensions', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether to include this folder in scans')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
