# Generated by Django 5.2.3 on 2025-08-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoSearch', '0009_mediafoldersetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyframe',
            name='transcript_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyframe',
            name='transcript_context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyframe',
            name='transcript_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
