# Generated by Django 5.2.3 on 2025-08-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoSearch', '0010_add_transcript_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyframe',
            name='transcript_embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
