# Generated by Django 5.2.3 on 2025-08-30 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoSearch', '0011_add_transcript_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(max_length=20, unique=True)),
                ('clip_weight', models.FloatField(default=1.0)),
                ('transcript_weight', models.FloatField(default=0.8)),
                ('dino_weight', models.FloatField(default=0.6)),
                ('object_weight', models.FloatField(default=0.4)),
                ('histogram_weight', models.FloatField(default=0.3)),
                ('training_samples', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('model_version', models.CharField(default='1.0', max_length=20)),
                ('click_through_rate', models.FloatField(blank=True, null=True)),
                ('average_result_position', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='SearchInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('query_type', models.CharField(choices=[('balanced', 'Balanced'), ('visual', 'Visual'), ('text', 'Text')], default='balanced', max_length=20)),
                ('search_timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=64, null=True)),
                ('had_filters', models.BooleanField(default=False)),
                ('filter_types', models.TextField(blank=True, null=True)),
                ('total_results_returned', models.IntegerField()),
                ('results_keyframe_ids', models.TextField()),
            ],
            options={
                'indexes': [models.Index(fields=['search_timestamp'], name='VideoSearch_search__a7b82e_idx'), models.Index(fields=['query_type'], name='VideoSearch_query_t_6b6b23_idx'), models.Index(fields=['had_filters'], name='VideoSearch_had_fil_52bbba_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResultClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_position', models.IntegerField()),
                ('click_timestamp', models.DateTimeField(auto_now_add=True)),
                ('time_to_click', models.FloatField()),
                ('view_duration', models.FloatField(blank=True, null=True)),
                ('next_action', models.CharField(blank=True, choices=[('new_search', 'New Search'), ('refine', 'Refine Search'), ('filter', 'Apply Filter'), ('download', 'Download'), ('exit', 'Exit')], max_length=20, null=True)),
                ('clicked_keyframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoSearch.keyframe')),
                ('search_interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoSearch.searchinteraction')),
            ],
            options={
                'indexes': [models.Index(fields=['result_position'], name='VideoSearch_result__03d791_idx'), models.Index(fields=['click_timestamp'], name='VideoSearch_click_t_a419c7_idx')],
                'unique_together': {('search_interaction', 'clicked_keyframe')},
            },
        ),
    ]
