# Generated by Django 5.2.3 on 2025-08-30 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoSearch', '0012_weightingmodel_searchinteraction_resultclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightingmodel',
            name='average_engagement_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weightingmodel',
            name='high_engagement_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weightingmodel',
            name='video_completion_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ResultEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_position', models.IntegerField()),
                ('was_clicked', models.BooleanField(default=False)),
                ('click_timestamp', models.DateTimeField(blank=True, null=True)),
                ('time_to_click', models.FloatField(blank=True, null=True)),
                ('view_duration', models.FloatField(default=0.0)),
                ('hover_duration', models.FloatField(default=0.0)),
                ('scroll_pauses', models.IntegerField(default=0)),
                ('video_played', models.BooleanField(default=False)),
                ('video_watch_duration', models.FloatField(default=0.0)),
                ('video_completion_rate', models.FloatField(default=0.0)),
                ('was_downloaded', models.BooleanField(default=False)),
                ('was_shared', models.BooleanField(default=False)),
                ('was_bookmarked', models.BooleanField(default=False)),
                ('was_used_as_filter', models.BooleanField(default=False)),
                ('opened_in_new_tab', models.BooleanField(default=False)),
                ('returned_to_result', models.BooleanField(default=False)),
                ('next_action', models.CharField(blank=True, choices=[('new_search', 'New Search'), ('refine', 'Refine Search'), ('apply_filter', 'Apply Filter'), ('download', 'Download'), ('share', 'Share'), ('bookmark', 'Bookmark'), ('continue_browsing', 'Continue Browsing'), ('exit', 'Exit')], max_length=20, null=True)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('keyframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoSearch.keyframe')),
                ('search_interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoSearch.searchinteraction')),
            ],
        ),
        migrations.DeleteModel(
            name='ResultClick',
        ),
        migrations.AddIndex(
            model_name='resultengagement',
            index=models.Index(fields=['result_position'], name='VideoSearch_result__81f6f9_idx'),
        ),
        migrations.AddIndex(
            model_name='resultengagement',
            index=models.Index(fields=['engagement_score'], name='VideoSearch_engagem_87ac84_idx'),
        ),
        migrations.AddIndex(
            model_name='resultengagement',
            index=models.Index(fields=['was_clicked'], name='VideoSearch_was_cli_d4201c_idx'),
        ),
        migrations.AddIndex(
            model_name='resultengagement',
            index=models.Index(fields=['video_played'], name='VideoSearch_video_p_03a495_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resultengagement',
            unique_together={('search_interaction', 'keyframe')},
        ),
    ]
