# Generated by Django 5.2.3 on 2025-08-30 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VideoSearch', '0013_weightingmodel_average_engagement_score_and_more'),
    ]

    operations = [
    ]
