# Generated by Django 5.2.3 on 2025-08-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoSearch', '0014_auto_20250830_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultengagement',
            name='clip_copied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resultengagement',
            name='related_searches_performed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultengagement',
            name='video_opened_fullscreen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resultengagement',
            name='video_scrubbed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resultengagement',
            name='next_action',
            field=models.CharField(blank=True, choices=[('new_search', 'New Search'), ('refine_search', 'Refine Search'), ('apply_filter', 'Apply Filter'), ('copy_clip', 'Copy Clip Info'), ('open_fullscreen', 'Open Fullscreen'), ('scrub_timeline', 'Scrub Timeline'), ('related_search', 'Search for Similar'), ('continue_browsing', 'Continue Browsing'), ('exit', 'Exit')], max_length=25, null=True),
        ),
    ]
