# Generated by Django 5.2.3 on 2025-08-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoSearch', '0015_resultengagement_clip_copied_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('embedding_clip', models.BinaryField()),
                ('embedding_dino', models.BinaryField(blank=True, null=True)),
                ('histogram_hsv', models.BinaryField(blank=True, null=True)),
                ('dominant_colors', models.BinaryField(blank=True, null=True)),
                ('colorfulness', models.FloatField(blank=True, null=True)),
                ('object_vector', models.BinaryField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'ordering': ['-upload_timestamp'],
                'indexes': [models.Index(fields=['upload_timestamp'], name='VideoSearch_upload__4be399_idx'), models.Index(fields=['session_key'], name='VideoSearch_session_f15352_idx')],
            },
        ),
    ]
