# Generated by Django 5.2.3 on 2025-09-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoSearch', '0016_uploadedframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyframe',
            name='ocr_bboxes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyframe',
            name='ocr_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyframe',
            name='ocr_embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyframe',
            name='ocr_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
